### ISSUE TITLE
Formatting the c source

### ISSUE THREAD

**Issue by pepe** [sepisoad/jurl#9]
Please would you consider to make simple format, where you remove whitespaces from the end of the lines, or even to start to use some formatting utility like astyle? 

In my C projects, I am using the default settings for astyle, which is also the one  @bakpakin uses for his C code.

It would really help to contribute to this project to me and others :-).

If you like to I will be more than happy to do it my self.

**Comment by sepisoad** [comment]
sure, why not my friend, however I am busy so you have to make the changes and I will merge them in the code.

**Comment by pepe** [comment]
Great! Thank you very much sir.
